### ISSUE TITLE
TypeError: Expected int32, got Dimension(300) of type 'Dimension' instead.

### ISSUE THREAD

**Issue by Bearsuny** [obryanlouis/qa#1]
Hi, obryanlouis. I am using TF ver 0.13 on Ubuntu 16.04 Python 3.6 without AWS s3 to train this repo commits ver [aa3bcf6](https://github.com/obryanlouis/qa/commit/aa3bcf6cff46f60ea391f7f2cf5fafcf60e41d88). I execute `python train_local.py` and got the following error. Could you please help me solve this error? Thanks a lot.
```
(baseline) bearsuny@Alien:~/Projects/qa$ python train_local.py
2017-12-18 16:01:42.348619: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-18 16:01:42.348643: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-18 16:01:42.348648: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-18 16:01:42.348653: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-18 16:01:42.348657: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-12-18 16:01:42.483406: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-18 16:01:42.483707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1060
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:01:00.0
Total memory: 5.92GiB
Free memory: 5.15GiB
2017-12-18 16:01:42.483724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-12-18 16:01:42.483731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-12-18 16:01:42.483739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
Vocab size: 2196016
1 train files batches, 1 dev
Creating towers
Creating tower in model
Traceback (most recent call last):
  File "train_local.py", line 13, in <module>
    tf.app.run()
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_local.py", line 10, in main
    Trainer(options).train()
  File "/home/bearsuny/Projects/qa/train/trainer.py", line 64, in train
    compute_gradients=True, sess=self.session)
  File "/home/bearsuny/Projects/qa/train/model_builder.py", line 23, in __init__
    self._setup()
  File "/home/bearsuny/Projects/qa/train/model_builder.py", line 83, in _setup
    iterators)
  File "/home/bearsuny/Projects/qa/train/model_builder.py", line 47, in _add_tower_and_compute_loss
    tower.setup()
  File "/home/bearsuny/Projects/qa/model/mnemonic_reader.py", line 16, in setup
    super(MnemonicReader, self).setup()
  File "/home/bearsuny/Projects/qa/model/base_model.py", line 53, in setup
    self.batch_size)
  File "/home/bearsuny/Projects/qa/model/input_util.py", line 145, in create_model_inputs
    ctx_inputs_list.append(_create_word_similarity(ctx_embedded, qst_embedded, v_wiq, batch_size))
  File "/home/bearsuny/Projects/qa/model/input_util.py", line 47, in _create_word_similarity
    prim = tf.reshape(primary_iterator, shape=[batch_size * W, N, 1])
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2619, in reshape
    name=name)
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 493, in apply_op
    raise err
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
    preferred_dtype=default_dtype)
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 676, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 937, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 899, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 376, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/bearsuny/anaconda3/envs/baseline/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got Dimension(300) of type 'Dimension' instead.

```

**Comment by obryanlouis** [comment]
Can you try on tf version 1.3 or higher? I haven't tested on versions below that.

**Comment by Bearsuny** [comment]
Sorry for my mistake. I wrote the wrong ver. I am using TF ver 1.3 rather 0.13...Here is my pip list:
```
attrs (17.3.0)
bleach (1.5.0)
boto3 (1.4.8)
botocore (1.8.13)
certifi (2017.11.5)
cffi (1.10.0)
chardet (3.0.4)
codecov (2.0.10)
cove (1.0.0, /home/bearsuny/Projects/cove)
coverage (4.4.2)
cymem (1.31.2)
cytoolz (0.8.2)
dill (0.2.7.1)
docutils (0.14)
en-core-web-sm (2.0.0)
enum34 (1.1.6)
flake8 (3.5.0)
ftfy (4.4.3)
html5lib (1.0.1)
idna (2.6)
jmespath (0.9.3)
Markdown (2.6.10)
mccabe (0.6.1)
msgpack-numpy (0.4.1)
msgpack-python (0.4.8)
murmurhash (0.28.0)
nltk (3.2.5)
numpy (1.13.3)
olefile (0.44)
pathlib (1.0.1)
Pillow (4.2.1)
pip (9.0.1)
plac (0.9.6)
pluggy (0.6.0)
preshed (1.0.0)
protobuf (3.5.0.post1)
py (1.5.2)
pycodestyle (2.3.1)
pycparser (2.18)
pyflakes (1.6.0)
pytest (3.3.1)
pytest-cov (2.5.1)
pytest-pythonpath (0.7.1)
python-dateutil (2.6.1)
regex (2017.4.5)
requests (2.18.4)
revtok (0.0.1)
s3transfer (0.1.12)
setuptools (38.2.4)
six (1.11.0)
spacy (2.0.5)
tensorflow-gpu (1.3.0)
tensorflow-tensorboard (0.1.8)
termcolor (1.1.0)
thinc (6.10.2)
toolz (0.8.2)
torch (0.3.0.post4)
torchtext (0.2.0)
torchvision (0.2.0)
tqdm (4.19.5)
ujson (1.35)
urllib3 (1.22)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.13)
wheel (0.30.0)
wrapt (1.10.11)

```

**Comment by obryanlouis** [comment]
Ah - I'm seeing this on 1.3 too. I upgraded to 1.4 a while ago and I don't check for backward compatibility. I will try to fix this soon and in the meantime you may try ver 1.4.

**Comment by Bearsuny** [comment]
Hi, I rewrite your code in the `model/input_util.py` line 43:
```
sh_prim = primary_iterator.get_shape().as_list()
sh_sec = secondary_iterator.get_shape().as_list()
```
and the error is gone and the train keep going. So, I want to know, is this correction right? The error seems to tell us that some variable should be int32, but got Dimension. So I just change the type of sh_prim and sh_sec. And I refer to the question in the stackoverflow: [How to get Tensorflow tensor dimensions (shape) as int values?](https://stackoverflow.com/questions/40666316/how-to-get-tensorflow-tensor-dimensions-shape-as-int-values)

**Comment by obryanlouis** [comment]
It looks good to me.

**Comment by Bearsuny** [comment]
thank you ~ Y(^_^)Y

**Comment by obryanlouis** [comment]
I didn't think anyone would actually use the code, but in case you are interested I put the parameters I used to get to my high score on the README. Hopefully that is useful in case you were trying to get the same result.

**Comment by Bearsuny** [comment]
Hi, again~ Thank you for your reply about your high score. Before your last reply, I have trained the `Mnemonic reader` model with your default option in the `flags.py` with GTX 1080Ti and tenserflow ver 1.4. And I got the following message: `Killedion: 316123 highest f1: 0.7206 learning rate: 2.647E-26 loss: 8.642E-01 Sec/iter: 0.531 time/epoch (min) 32.304`
The terminal output log before the message are following:
```
[Train] F1 0.9340566686776811 Em 0.8456160241874527

[Valid] F1 0.713798777587896 Em 0.6111636707663197
Time to evaluate train/val: 168.240000
Dropped learning rate to 2.647E-26 because val F1 didn't increase from 7.206E-01
Total epoch time (min) 34.903
Cumulative run time (hr) 50.094
iteration: 313900 highest f1: 0.7206 learning rate: 2.647E-26 loss: 1.452E+00 Sec/iter: 0.528 time/epoch (min) 32.122
[Validation] iteration: 313900 loss: 3.756E+00
... ...
[Validation] iteration: 316000 loss: 6.059E+00
iteration: 316100 highest f1: 0.7206 learning rate: 2.647E-26 loss: 1.496E+00 Sec/iter: 0.531 time/epoch (min) 32.315
[Validation] iteration: 316100 loss: 9.588E+00
Killedion: 316123 highest f1: 0.7206 learning rate: 2.647E-26 loss: 8.642E-01 Sec/iter: 0.531 time/epoch (min) 32.304
```
Did it mean that the train has finished? I reviewed your code in trainer.py and I didn't find the word "Killedion" and I also didn't find the way to finish training in your code. Could you tell me during the training, when or how to finish the train?

And during the traing, I found about 54 terminal output logs are all like following
```
[Train] F1 0.9298234563897113 Em 0.8451436130007559

[Valid] F1 0.7137896380378973 Em 0.6118259224219489
Time to evaluate train/val: 167.894738
Dropped learning rate to 5.294E-26 because val F1 didn't increase from 7.206E-01
```

The number 54 is huge, because the total of output logs is about 87. Does it mean that the last 54 epoch is unnecessary?

After that, I execute the evaluation, and I got the result within your default option:
```
Writing context, question, ground truth, and predictions to files in evaluation dir [evaluation_results]
Dev Em: 0.6199621570482498 Dev F1: 0.7206311747570326
```

**Comment by obryanlouis** [comment]
"Killed" generally means that the program ran out of memory, but I think that could be expected if it runs for so long and other programs take memory. There is no built-in stopping mechanism to the program, it just runs until you want to stop it. I generally stop it when the validation f1 score looks like it won't go up anymore. I guess that could be improved by some automatic mechanism that breaks whenever the score doesn't go up for some amount of epochs.

Whenever the reaches a new epoch it prints the EM/F1 scores like you see above. If it reaches an epoch with better f1, then it saves the model. Your final score was 72% f1/62% em. I think there were a couple of issues in the version you checked out that could have made the score lower than the stated one, so you can try checking out commit 16b9d2d18b5873f8d84bdd9f6cb4151f27789314 and running with the same params I used.

I used something like
`python train_local.py --model_type=mnemonic_reader --rnn_size=60 --use_cove_vectors=True --batch_size=50 --num_gpus=2 --dropout=0.3 --experiment_name=rnn60`
The batch size / num gpu's doesn't seem to matter that much as long as the batch size is < 100ish total.

**Comment by Bearsuny** [comment]
Thank you for your detailed reply. :+1: I got it. I will try your parameter to train the `Mnemonic reader` model . (ﾉ･ω･)ﾉﾞ

**Comment by Bearsuny** [comment]
After training `mnemnic_reader` model with your parameter, I got the similar results with yours. When the training achieved the following F1 and EM, I stopped the program.
```
[Train] F1 0.8708615640675781 Em 0.7397169811320755

[Valid] F1 0.8053730285991096 Em 0.7111636707663198
Time to evaluate train/val: 121.163318
Dropped learning rate to 1.250E-04 because val F1 didn't increase from 8.064E-01
Total epoch time (min) 19.311
Cumulative run time (hr) 7.438
```
 And I evaluated the trained model. Here is my results:
```
Writing context, question, ground truth, and predictions to files in evaluation dir [evaluation_results]
Dev Em: 0.714569536423841 Dev F1: 0.8063717237268204
```
So thank you for your previous detailed reply. It's time to close this issue. ~(ﾉ･ω･)ﾉ~

**Comment by obryanlouis** [comment]
Great! Good luck training.
