### ISSUE TITLE
sre_constants.error: bad escape \c at position 10

### ISSUE THREAD

**Issue by Chunlinx** [obryanlouis/qa#7]
Hi, obryanlouis,
I tried to train the model and got an error as below:
Traceback (most recent call last):
  File "train_local.py", line 13, in <module>
    tf.app.run()
  File "C:\Program Files\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_local.py", line 10, in main
    Trainer(options).train()
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\train\trainer.py", line 43, in train
    self.sq_dataset = create_sq_dataset(self.options)
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\train\model_util.py", line 19, in create_sq_dataset
    return TestData(options) if options.use_fake_dataset else SquadData(options)
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\datasets\squad_data.py", line 198, in __init__
    self.train_ds = _SquadDataset(training_dir, options, self.vocab)
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\datasets\squad_data.py", line 52, in __init__
    constants.CONTEXT_FILE_PATTERN)
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\util\file_util.py", line 9, in get_data_files_list
    return sorted([f for f in all_files_in_files_dir \
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\util\file_util.py", line 10, in <listcomp>
    if re.match(search_pattern, f)])
  File "C:\Program Files\Python36\lib\re.py", line 172, in match
    return _compile(pattern, flags).match(string)
  File "C:\Program Files\Python36\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Program Files\Python36\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Program Files\Python36\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Program Files\Python36\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Program Files\Python36\lib\sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "C:\Program Files\Python36\lib\sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \c at position 10

Can you please tell me why this happend?

**Comment by obryanlouis** [comment]
You didn't happen to change the constants.py file did you? It looks like it's complaining about the regex on this line:

CONTEXT_FILE_PATTERN = "context.%d.npy"

The error seems similar to https://bugs.python.org/issue27471 but I don't see where there is even a "\c" anywhere.

**Comment by Chunlinx** [comment]
I changed the python version to 3.5 and it's working now , but got another error:
Traceback (most recent call last):
  File "train_local.py", line 13, in <module>
    tf.app.run()
  File "D:\python\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "train_local.py", line 10, in main
    Trainer(options).train()
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\train\trainer.py", line 43, in train
    self.sq_dataset = create_sq_dataset(self.options)
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\train\model_util.py", line 19, in create_sq_dataset
    return TestData(options) if options.use_fake_dataset else SquadData(options)
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\datasets\squad_data.py", line 198, in __init__
    self.train_ds = _SquadDataset(training_dir, options, self.vocab)
  File "D:\CHUNLINXU\2018\qa-2-master\qa-2-master\datasets\squad_data.py", line 76, in __init__
    assert len(self.context_files) > 0
AssertionError

Can you please help me solve this error?

**Comment by obryanlouis** [comment]
Can you verify that you ran the "setup.py" file? And if so, can you also check that there are files located under data/train and data/dev?

**Comment by Chunlinx** [comment]
yes,I have run the "setup.py", and there are files in the data/train and data/dev.

**Comment by obryanlouis** [comment]
Ok - strange. That assertion is basically saying that there are no files found for training. My data directory structure looks something like this:

data
data/char.txt
data/vocab.chars.npy
data/glove.embedding.npy
data/train
data/train/question_ids_to_squad_question_id.0
data/train/word_in_question.0.npy
data/train/span.0.npy
data/train/question.ner.0.npy
data/train/context.ner.0.npy
data/train/question_ids.0.npy
data/train/context.pos.0.npy
data/train/question.pos.0.npy
data/train/context.0.npy
data/train/passage_context.0
data/train/question.0.npy
data/train/word_in_context.0.npy
data/cove_weights
data/cove_weights/bias_ih_l1.npy
data/cove_weights/bias_ih_l1_reverse.npy
data/cove_weights/weight_ih_l0_reverse.npy
data/cove_weights/bias_hh_l1.npy
data/cove_weights/bias_hh_l1_reverse.npy
data/cove_weights/weight_ih_l1.npy
data/cove_weights/bias_hh_l0.npy
data/cove_weights/bias_ih_l0_reverse.npy
data/cove_weights/weight_ih_l1_reverse.npy
data/cove_weights/weight_hh_l0.npy
data/cove_weights/bias_ih_l0.npy
data/cove_weights/weight_hh_l1_reverse.npy
data/cove_weights/bias_hh_l0_reverse.npy
data/cove_weights/weight_ih_l0.npy
data/cove_weights/weight_hh_l1.npy
data/cove_weights/weight_hh_l0_reverse.npy
data/vocab.txt
data/dev
data/dev/question_ids_to_squad_question_id.0
data/dev/word_in_question.0.npy
data/dev/span.0.npy
data/dev/question.ner.0.npy
data/dev/context.ner.0.npy
data/dev/question_ids.0.npy
data/dev/context.pos.0.npy
data/dev/question.pos.0.npy
data/dev/context.0.npy
data/dev/passage_context.0
data/dev/question.0.npy
data/dev/word_in_context.0.npy

I assume yours is similar. I would recommend that you try debugging what the file pattern it is searching for is. 

Try running this at the top level directory to see if you have any output:

import preprocessing.constants as constants
import glob
import os
import re

dir_name = "data/train"
file_name_pattern = constants.CONTEXT_FILE_PATTERN
search_pattern = os.path.join(dir_name,
    file_name_pattern.replace("%d", "[0-9]+"))
all_files_in_files_dir = glob.glob(os.path.join(dir_name, "*"))
files_matching_pattern = sorted([f for f in all_files_in_files_dir \
    if re.match(search_pattern, f)])
print("dir_name", dir_name)
print("file_name_pattern", file_name_pattern)
print("search_pattern", search_pattern)
print("all_files_in_files_dir", all_files_in_files_dir)
print("files_matching_pattern", files_matching_pattern)

I see the following:
dir_name data/train
file_name_pattern context.%d.npy
search_pattern data/train/context.[0-9]+.npy
all_files_in_files_dir ['data/train/question_ids_to_squad_question_id.0', 'data/train/word_in_question.0.npy', 'data/train/span.0.npy', 'data/train/question.ner.0.npy', 'data/train/context.ner.0.npy', 'data/train/question_ids.0.npy', 'data/train/context.pos.0.npy', 'data/train/question.pos.0.npy', 'data/train/context.0.npy', 'data/train/passage_context.0', 'data/train/question.0.npy', 'data/train/word_in_context.0.npy']
files_matching_pattern ['data/train/context.0.npy']

I am on python 3.6.3 if that helps

**Comment by obryanlouis** [comment]
I'm going to close this since it's been a while without any activity.
